export declare const API_VERSION = "v1";
export declare const API_PREFIX = "/api/v1";
export declare const DEFAULT_CURRENCY = "BBD";
export declare const DEFAULT_COUNTRY = "BB";
export declare const DEFAULT_CURRENCY_DECIMALS = 2;
export declare const JWT_ACCESS_TTL_SECONDS = 900;
export declare const JWT_REFRESH_TTL_SECONDS = 604800;
export declare const MAX_PIN_ATTEMPTS = 5;
export declare const PIN_LOCKOUT_MINUTES = 30;
export declare const IDEMPOTENCY_KEY_HEADER = "idempotency-key";
export declare const CORRELATION_ID_HEADER = "x-correlation-id";
export declare const REQUEST_ID_HEADER = "x-request-id";
export declare const OUTBOX_POLL_INTERVAL_MS = 1000;
export declare const OUTBOX_MAX_RETRIES = 5;
export declare const OUTBOX_BATCH_SIZE = 50;
export declare const ROUNDING_MODE = "HALF_EVEN";
//# sourceMappingURL=constants.d.ts.map